//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTIST
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string BORN { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string DESCRIP { get; set; }
        public string TW { get; set; }
        public string FB { get; set; }
        public Nullable<short> ID_LABEL { get; set; }
        public string IMG { get; set; }
        public string NAME_LABEL { get; set; }
        public Nullable<int> POINT_MONTH { get; set; }
        public Nullable<int> POINT_ALL { get; set; }
    }
}
