//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHART
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> DATE_RELEASE { get; set; }
        public string DESCRIP { get; set; }
        public string NAME_GENRE { get; set; }
        public string LINK_IMG { get; set; }
        public Nullable<double> COST { get; set; }
        public Nullable<short> ID_GENRE { get; set; }
        public Nullable<byte> TYPE { get; set; }
    
        public virtual GENRE GENRE { get; set; }
    }
}
