//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENRE_LABEL
    {
        public short ID_LABEL { get; set; }
        public short ID_GENRE { get; set; }
        public string NAME_GENRE { get; set; }
        public Nullable<int> POINT { get; set; }
    
        public virtual GENRE GENRE { get; set; }
        public virtual LABEL LABEL { get; set; }
    }
}
