//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTEN_SLIDER
    {
        public int ID { get; set; }
        public string NAME_SONG { get; set; }
        public Nullable<double> COST { get; set; }
        public string LINK { get; set; }
        public string LINK_IMG { get; set; }
        public string DESCRIPT { get; set; }
        public string GENRE { get; set; }
        public string LENGHT { get; set; }
        public string ARTISTS { get; set; }
    }
}
