//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHOW_LIST
    {
        public int ID { get; set; }
        public string NAME_SHOW { get; set; }
        public string ARTIST_SHOW { get; set; }
        public string LOCATION { get; set; }
        public string TIME { get; set; }
        public string LINK_IMG { get; set; }
        public string DESCRIBLE { get; set; }
    }
}
