//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATISTIC_REMIX
    {
        public int ID { get; set; }
        public Nullable<int> CLICK_ALL { get; set; }
        public Nullable<int> CLICK_MONTH { get; set; }
        public Nullable<int> BUY_ALL { get; set; }
        public Nullable<int> BUY_MONTH { get; set; }
        public Nullable<int> POINT_MONTH { get; set; }
        public Nullable<int> POINT_ALL { get; set; }
    
        public virtual REMIX REMIX { get; set; }
    }
}
