//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STEM()
        {
            this.STEM_ARTIST = new HashSet<STEM_ARTIST>();
            this.STEM_ARTIST1 = new HashSet<STEM_ARTIST>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<byte> TEMPO { get; set; }
        public string KEY_ { get; set; }
        public Nullable<double> COST { get; set; }
        public string LINK { get; set; }
        public string LINK_IMG { get; set; }
        public string DESCRIP { get; set; }
        public string LENGTH { get; set; }
        public Nullable<int> POINT_MONTH { get; set; }
        public Nullable<int> POIN_ALL { get; set; }
        public Nullable<int> STEMS_ID { get; set; }
        public string GENRE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STEM_ARTIST> STEM_ARTIST { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STEM_ARTIST> STEM_ARTIST1 { get; set; }
    }
}
