//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STEM_ARTIST
    {
        public int STEM_ID { get; set; }
        public int ARTIST_ID { get; set; }
        public string ARTIST_NAME { get; set; }
        public string NAME_LABEL { get; set; }
        public string NAME_STEM { get; set; }
    
        public virtual ARTIST ARTIST { get; set; }
        public virtual STEM STEM { get; set; }
        public virtual STEM STEM1 { get; set; }
    }
}
