//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMusic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STEM1
    {
        public int STEMS_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> DATE_RELEASE { get; set; }
        public Nullable<double> COST { get; set; }
        public string CATALOG { get; set; }
        public string IMG { get; set; }
    }
}
